### PR TITLE
fix invalid format of DefaultTransmissionDateTimeFormat

### LINKED ISSUE #36: invalid format for DefaultTransmissionDateTimeFormat const
The constant DefaultTransmissionDateTimeFormat has an invalid format https://github.com/moov-io/iso8583-connection/blob/cc16efa1ef07b3059395cf6a01d47613556bab93/connection.go#L23

This patch fixes it

```diff
Index: connection.go
===================================================================
diff --git a/connection.go b/connection.go
--- a/connection.go	(revision cc16efa1ef07b3059395cf6a01d47613556bab93)
+++ b/connection.go	(date 1681109924553)
@@ -20,7 +20,7 @@
 	ErrSendTimeout      = errors.New("message send timeout")
 )
 
-const DefaultTransmissionDateTimeFormat string = "0102150405" // YYMMDDhhmmss
+const DefaultTransmissionDateTimeFormat string = "060102150405" // YYMMDDhhmmss
 
 // MessageLengthReader reads message header from the r and returns message length
 type MessageLengthReader func(r io.Reader) (int, error)

```

### PR DESCRIPTION
**Pull request by jerome-laforge**
Fixes https://github.com/moov-io/iso8583-connection/issues/36

### CODE REVIEW

**Review by adamdecaf — APPROVED** [review]

**Comment by alovak** [comment]
I see two issues with `DefaultTransmissionDateTimeFormat` and this PR 🙈:
* the constant is not used inside the package (it was used in times when we set processing time for the message, but then we removed that code and forgot about the constant)
* if we decide to accept the fix, then it should fix the comment, not the format :)

but, I think we should just remove it. It may be a breaking change, but taking into account the version of our package and the meaning of the constant it's ok.

**Comment by jerome-laforge** [comment]
It is OK for me to remove it.

**Comment by adamdecaf** [comment]
Removing the constant is fine since we don't use it. Callers who use it can copy whichever version they need.

**Comment by alovak** [comment]
closing in favour of https://github.com/moov-io/iso8583-connection/pull/38

**Pull request closed without merging**
